config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  #get 'travel', to: 'pages#travel'
  get 'soul', to: 'pages#soul'
  get 'career', to: 'pages#career'
  get 'money', to: 'pages#money'
  get 'health', to: 'pages#health'
  get 'relationships', to: 'pages#relationships'
  get 'products', to: 'pages#products'
  get 'household', to: 'pages#household'

  resources :travel, only: [:index] do
  get 'travel', to: 'travel#index'
    collection do
      get "t_article1", to: "travel#t_article1"
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def travel
  end

  def soul
  end

  def career
  end

  def money
  end

  def health
  end

  def relationships
  end

  def products
  end

  def household
  end
end

app/controllers/travel_controller.rb
class TravelController < ApplicationController

  def index
  end

  def t_article1
    #@travel = travel
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Howtoadult</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <%= render "shared/navbar" %>

  <%= yield %>

  <%= render "shared/footer" %>

</body>
</html>

app/views/pages/career.html.erb
<h1>Pages#career</h1>
<p>Find me in app/views/pages/career.html.erb</p>

app/views/pages/health.html.erb
<h1>Pages#health</h1>
<p>Find me in app/views/pages/health.html.erb</p>

app/views/pages/home.html.erb
<div class="container">
  <div class="category-banner">

    <div class="introduction-text">
      <h3>
        simple answers to those "i don't know" moments... <br>
      </h3>
    </div>
    <div class="sub-header-text">
      <p> Discover answers by category:</p>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card travel-colored red-border-top" >
          <div class="card-description">
            <h2>Travel</h2>
            <p>where should I explore next</p>
          </div>
          <%= link_to "", travel_index_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card career-colored orange-border-top" >
          <div class="card-description">
            <h2>Career</h2>
            <p>where can I add value</p>
          </div>
          <%= link_to "", career_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card soul-colored yellow-border-top" >
          <div class="card-description">
            <h2>Soul</h2>
            <p>what should I do with my time</p>
          </div>
          <%= link_to "", soul_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card money-colored green-border-top" >
          <div class="card-description">
            <h2>Money</h2>
            <p>how do I afford what I need</p>
          </div>
          <%= link_to "", money_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card health-colored blue-border-top" >
          <div class="card-description">
            <h2>Health</h2>
            <p>how to be my healthiest self</p>
          </div>
          <%= link_to "", health_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card relationship-colored purple-border-top" >
          <div class="card-description">
            <h2>Relationships</h2>
            <p>build meaningful connections</p>
          </div>
          <%= link_to "", relationships_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card product-colored pink-border-top" >
          <div class="card-description">
            <h2>Products</h2>
            <p>what is worth my money</p>
          </div>
          <%= link_to "", products_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card homelife-colored gray-border-top" >
          <div class="card-description">
            <h2>Homelife</h2>
            <p>what makes a home</p>
          </div>
          <%= link_to "", household_path, :class => "card-link" %>
        </div>
      </div>
    </div>
  </div>
  <div class="home-featured-articles">
    <div class="sub-header-text">
      <p> Top Articles this Month </p>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <div class="row">
          <div class="col-xs-12 col-md-3">
            <div class="featured-card red-fill travel-colored" >
              <div class="featured-card-description">
                <p>where should I explore next</p>
                <p>Travel</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="featured-card orange-fill career-colored" >
              <div class="featured-card-description">
                <p>where can I add value</p>
                <p>Career</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="featured-card green-fill money-colored" >
              <div class="featured-card-description">
                <p>where can I add value</p>
                <p>Career</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="featured-card purple-fill relationship-colored" >
              <div class="featured-card-description">
                <p>where can I add value</p>
                <p>Career</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-3">
            <div class="featured-card pink-fill product-colored" >
              <div class="featured-card-description">
                <p>where can I add value</p>
                <p>Career</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="featured-card blue-fill health-colored" >
              <div class="featured-card-description">
                <p>where can I add value</p>
                <p>Career</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="featured-card gray-fill homelife-colored">
              <div class="featured-card-description">
                <p>where can I add value</p>
                <p>Career</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="featured-card yellow-fill soul-colored" >
              <div class="featured-card-description">
                <p>where can I add value</p>
                <p>Career</p>
              </div>
              <a class="featured-card-link" href="#" ></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/household.html.erb
<h1>Pages#household</h1>
<p>Find me in app/views/pages/household.html.erb</p>

app/views/pages/money.html.erb
<h1>Pages#money</h1>
<p>Find me in app/views/pages/money.html.erb</p>

app/views/pages/products.html.erb
<h1>Pages#products</h1>
<p>Find me in app/views/pages/products.html.erb</p>

app/views/pages/relationships.html.erb
<h1>Pages#relationships</h1>
<p>Find me in app/views/pages/relationships.html.erb</p>

app/views/pages/soul.html.erb
<h1>Pages#soul</h1>
<p>Find me in app/views/pages/soul.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-youtube"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at How to Adult
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="https://pbs.twimg.com/profile_images/1019516401571287040/IMHq8vUO_400x400.jpg" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link red-text">Travel</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link orange-text">Career</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link yellow-text">Soul</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link green-text">Money</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link blue-text">Health</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link purple-text">Relationships</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link pink-text">Products</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link gray-text">Homelife</a>

    <!-- Profile picture with dropdown list -->
    <!--
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  -->
  </div>

  <!-- Dropdown appearing on mobile only -->
  <!--
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
-->
</div>

app/views/travel/index.html.erb
<div class="container">
  <div class="category-banner">
    <div class="introduction-text-category">
      <h3>
        <span class="red-text-box">
        Go somewhere you've never been before...</span>
      </h3>
    </div>

    <div class="sub-header-text">
      <h5 class="red-text"> Travel </h5>
      <p class="cateogry-text-padding-left"> The Essentails </p>
    </div>
<!--    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="category-card" >
          <div class="travel-"></div>
          <div class="category-card-description">
            <h2><span>The Top Places to Travel in the World</span> </h2>
            <p><span>A budget-friendly guide for what to see without the crowds</span></p>
          </div>
          <%= link_to "", travel_index_path, :class => "category-card-link" %>
        </div>
      </div>
    </div> -->
    <div class="row">
     <div class="col-xs-12 col-lg-6">
      <div class="category-list-item" >
        <img class="category-list-photo" src="https://images.unsplash.com/photo-1508672019048-805c876b67e2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1693&q=80">
        <div class="category-list-description">
          <h2 class="red-text"><span>The Top Places to Travel in the World</span> </h2>
          <h3><span>A budget-friendly guide for what to see without the crowds</span></h3>
          <div class="reading-time">
            <i class="far fa-clock red-text"></i>
            <p><span>Reading Time: < 5 min</span></p>
          </div>
        </div>
        <%= link_to "", t_article1_travel_index_path, :class => "category-card-link" %>
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="category-list-item" >
        <img class="category-list-photo" src="https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1308&q=80">
        <div class="category-list-description">
          <h2 class="red-text"><span>The Top Places to Travel in the World</span> </h2>
          <h3><span>A budget-friendly guide for what to see without the crowds</span></h3>
          <div class="reading-time">
            <i class="far fa-clock red-text"></i>
            <p><span>Reading Time: < 5 min</span></p>
          </div>
        </div>
        <%= link_to "", travel_index_path, :class => "category-card-link" %>
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="category-list-item" >
        <img class="category-list-photo" src="https://images.unsplash.com/photo-1500835556837-99ac94a94552?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80">
        <div class="category-list-description">
          <h2 class="red-text"><span>The Top Places to Travel in the World</span> </h2>
          <h3><span>A budget-friendly guide for what to see without the crowds</span></h3>
          <div class="reading-time">
            <i class="far fa-clock red-text"></i>
            <p><span>Reading Time: 10-15 min</span></p>
            <i class="fa fa-trophy gold-text" aria-hidden="true"></i>
            <p><span>Readers Choice</span></p>
          </div>
        </div>
        <%= link_to "", travel_index_path, :class => "category-card-link" %>
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="category-list-item" >
        <img class="category-list-photo" src="https://images.unsplash.com/photo-1500815845799-7748ca339f27?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=564&q=80">
        <div class="category-list-description">
          <h2 class="red-text"><span>The Top Places to Travel in the World</span> </h2>
          <h3><span>A budget-friendly guide for what to see without the crowds</span></h3>
          <div class="reading-time">
            <i class="far fa-clock red-text"></i>
            <p><span>Reading Time: < 5 min</span></p>
          </div>
        </div>
        <%= link_to "", travel_index_path, :class => "category-card-link" %>
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="category-list-item" >
        <img class="category-list-photo" src="https://images.unsplash.com/photo-1475688621402-4257c812d6db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80">
        <div class="category-list-description">
          <h2 class="red-text"><span>The Top Places to Travel in the World</span> </h2>
          <h3><span>A budget-friendly guide for what to see without the crowds</span></h3>
          <div class="reading-time">
            <i class="far fa-clock red-text"></i>
            <p><span>Reading Time: 5-10 min</span></p>
          </div>
        </div>
        <%= link_to "", travel_index_path, :class => "category-card-link" %>
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="category-list-item" >
        <img class="category-list-photo" src="https://images.unsplash.com/photo-1484804959297-65e7c19d7c9f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1314&q=80">
        <div class="category-list-description">
          <h2 class="red-text"><span>The Top Places to Travel in the World</span> </h2>
          <h3><span>A budget-friendly guide for what to see without the crowds</span></h3>
          <div class="reading-time">
            <i class="far fa-clock red-text"></i>
            <p><span>Reading Time: < 5 min</span></p>
          </div>
        </div>
        <%= link_to "", travel_index_path, :class => "category-card-link" %>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<div class="featured-header-text">
  <h5 class="red-text"> Featured Article </h5>
  <p class="cateogry-text-padding-left light-gray-text"> Important Information People </p>
</div>
<div class="featured-article" style="background-image: linear-gradient(-225deg, rgba(255,255,255,0.3) 0%, rgba(255,255,255,0.3) 50%), url('https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1308&q=80');">
  <div class="featured-article-content">
    <h1 class="red-text"><span>The Top Places to Travel in the World</span></h1>
    <p class="light-gray-text">A budget-friendly guide for what to see without the crowds</p>
    <a class="btn red-btn btn-lg">Discover</a>
  </div>
</div>
<div class="container">
  <div class="category-banner">
<div class="sub-header-text">
      <h5 class="black-text"> Crossover Articles </h5>
      <p class="cateogry-text-padding-left"> Popular Articles you Might Also Like </p>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-md-2">
        <div class="card travel-colored red-border-top" >
          <div class="card-description">
            <h2> The 10 places to explore next year</h2>
            <p> Stop dragging your partners ass around the world and take charge </p>
          </div>
          <%= link_to "", travel_index_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-2">
        <div class="card career-colored orange-border-top" >
          <div class="card-description">
            <h2>Career</h2>
            <p>where can I add value</p>
          </div>
          <%= link_to "", career_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-2">
        <div class="card soul-colored yellow-border-top" >
          <div class="card-description">
            <h2>Soul</h2>
            <p>what should I do with my time</p>
          </div>
          <%= link_to "", soul_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-2">
        <div class="card money-colored green-border-top" >
          <div class="card-description">
            <h2>Money</h2>
            <p>how do I afford what I need</p>
          </div>
          <%= link_to "", money_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-2">
        <div class="card health-colored blue-border-top" >
          <div class="card-description">
            <h2>Health</h2>
            <p>how to be my healthiest self</p>
          </div>
          <%= link_to "", health_path, :class => "card-link" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-3 col-md-2">
        <div class="card relationship-colored purple-border-top" >
          <div class="card-description">
            <h2>Relationships</h2>
            <p>build meaningful connections</p>
          </div>
          <%= link_to "", relationships_path, :class => "card-link" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/travel/t_article1.html.erb
<h1> Travel article 1 try 2</h1>